# -*- coding: utf-8 -*-
"""takemeter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABbHaRgXVYz_oKVW7CcrmBKyXiPYkKE7

## Section 1: Define Label Map and Upload Data

This section loads your labeled dataset (`takemeter_dataset.csv`) and defines the label mapping. Since you've already uploaded the CSV, I'll load it directly. You might need to adjust the `label_map` based on your specific dataset's labels.
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from collections import Counter
import os

# Load the dataset
df = pd.read_csv('/content/takemeter_dataset.csv')

print("Dataset loaded successfully. Displaying first 5 rows:")
display(df.head())

# Placeholder for your label map
# Assuming your dataset has a 'label' column and a 'text' column for classification.
# Please modify this dictionary based on your actual labels and their desired numerical representation.
# Example: label_map = {'positive': 0, 'negative': 1, 'neutral': 2}

# --- IMPORTANT: Adjust the 'label_column' and 'text_column' to match your CSV file ---
label_column = 'label' # Replace with the actual name of your label column
text_column = 'text'   # Replace with the actual name of your text content column

# Infer unique labels and create a basic label_map if not explicitly defined
if label_column in df.columns:
    unique_labels = df[label_column].unique()
    label_map = {label: i for i, label in enumerate(sorted(unique_labels))}
    print(f"\nInferred Label Map: {label_map}")
else:
    print(f"\nWarning: '{label_column}' column not found. Please update 'label_column' and define 'label_map'.")
    label_map = {}

# Apply the label map (if a label column exists and map is not empty)
if label_column in df.columns and label_map:
    df['encoded_label'] = df[label_column].map(label_map)
    if df['encoded_label'].isnull().any():
        print("Warning: Some labels were not found in the label_map. Please ensure all labels are included.")

"""## Section 2: Dataset Split and Tokenization

This section splits your dataset into training, validation, and test sets (70%/15%/15%) and tokenizes the text content. We'll use a generic tokenizer from the `transformers` library. You might need to install it if not already present.
"""

# Install transformers if not already installed
try:
    import transformers
except ImportError:
    !pip install transformers datasets accelerate -qqq
    import transformers

from transformers import AutoTokenizer

# Ensure the label column and text column exist and encoded_label is present
if label_column not in df.columns or text_column not in df.columns or 'encoded_label' not in df.columns:
    raise ValueError("Please ensure 'label_column', 'text_column' and 'encoded_label' are correctly set up in Section 1.")

# Split the dataset into training (70%), validation (15%), and test (15%)
# Using stratify to maintain label distribution in splits
X = df[text_column]
y = df['encoded_label']

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"\nTraining set size: {len(X_train)}")
print(f"Validation set size: {len(X_val)}")
print(f"Test set size: {len(X_test)}")

print("\nTraining label distribution:", Counter(y_train))
print("Validation label distribution:", Counter(y_val))
print("Test label distribution:", Counter(y_test))

# Initialize a tokenizer (you can choose a different model if needed)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(texts):
    return tokenizer(texts.tolist(), truncation=True, padding=True)

# Tokenize all splits
print("\nTokenizing training data...")
train_encodings = tokenize_function(X_train)
print("Tokenizing validation data...")
val_encodings = tokenize_function(X_val)
print("Tokenizing test data...")
test_encodings = tokenize_function(X_test)

print("Tokenization complete.")

from google.colab import drive
drive.mount('/content/drive')

"""## Section 5: Baseline with Groq API

This section sets up your Groq API key and defines the classification prompt for your zero-shot baseline. Remember to add your Groq API key to Colab Secrets under the name `GROQ_API_KEY` or replace `userdata.get('GROQ_API_KEY')` with your key directly (not recommended for sharing).
"""

from google.colab import userdata
import requests
import json

# Get your Groq API key from Colab Secrets
GROQ_API_KEY = userdata.get('GROQ_API_KEY')

if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY not found in Colab Secrets. Please add it.")

# Pre-compute the string of categories from label_map for the prompt
label_categories_str = ', '.join(label_map.keys())

# Define your classification prompt template
# Use placeholders {categories} and {text_to_classify} to be filled later
classification_prompt_template = """
You are an expert text classifier. Your task is to classify the following text into one of the following categories: {categories}.

Output ONLY the label name. Do not include any other text, punctuation, or explanations.

Text: {text_to_classify}
Label:
"""

def get_groq_completion(prompt):
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }
    data = {
        "model": "llama-3.3-70b-versatile", # Updated model to a currently supported one
        "messages": [{
            "role": "user",
            "content": prompt
        }],
        "temperature": 0.0 # Set to 0 for deterministic output
    }
    response = requests.post("https://api.groq.com/openai/v1/chat/completions", headers=headers, json=data)
    # Check for non-2xx status codes and print more details
    if not response.ok:
        print(f"Groq API Error Status: {response.status_code}")
        print(f"Groq API Error Response: {response.text}")
        response.raise_for_status() # Still raise, but after printing details
    return response.json()['choices'][0]['message']['content'].strip()

# Run baseline on the test set
predictions = []
actual_labels = y_test.tolist()

print("\nRunning baseline classification on the test set... This might take a while.")

# Define a maximum character limit for the text to prevent exceeding context window
MAX_TEXT_LENGTH = 500 # Reduced further for testing

for i, text in enumerate(X_test):
    if i % 100 == 0: # Print progress every 100 examples
        print(f"Processed {i}/{len(X_test)} examples")

    # Truncate text if it's too long
    truncated_text = text[:MAX_TEXT_LENGTH] if len(text) > MAX_TEXT_LENGTH else text

    # Replace placeholders in the prompt with actual values
    formatted_prompt = classification_prompt_template.format(categories=label_categories_str, text_to_classify=truncated_text)
    try:
        prediction = get_groq_completion(formatted_prompt)
        predictions.append(prediction)
    except Exception as e:
        print(f"Error classifying text: {text}. Error: {e}")
        predictions.append("UNPARSEABLE") # Mark as unparseable

print("Baseline classification complete.")

# Evaluate baseline results
from sklearn.metrics import accuracy_score, classification_report

# Convert predicted labels back to numerical if possible for evaluation
# Create a reverse label map for conversion
reverse_label_map = {v: k for k, v in label_map.items()}

# Filter out unparseable predictions for accuracy calculation
clean_actual_labels = []
clean_predictions = []
unparseable_count = 0

for i in range(len(predictions)):
    if predictions[i] in label_map:
        clean_predictions.append(label_map[predictions[i]])
        clean_actual_labels.append(actual_labels[i])
    else:
        unparseable_count += 1

print(f"\nTotal unparseable responses: {unparseable_count}/{len(predictions)}")

if clean_actual_labels:
    print(f"Overall Accuracy: {accuracy_score(clean_actual_labels, clean_predictions):.4f}")
    print("\nClassification Report (for parseable predictions):\n") # Corrected string literal
    target_names = [reverse_label_map[i] for i in sorted(list(set(clean_actual_labels + clean_predictions)))]
    print(classification_report(clean_actual_labels, clean_predictions, target_names=target_names))
else:
    print("No parseable predictions to evaluate accuracy or generate classification report.")

# Reflect briefly: where did the baseline struggle? Are there specific labels it consistently confuses?
# Write down your hypothesis — you'll test it after fine-tuning.

"""## Section 3: Fine-Tune Your Model

This section loads the `distilbert-base-uncased` model and fine-tunes it on your training data. Training will take 5-15 minutes on a T4 GPU. The default settings are 3 epochs, learning rate 2e-5, and batch size 16. You can modify the `TrainingArguments` if needed.
"""

import torch
from transformers import DistilBertForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import Dataset

# Check for GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    device = torch.device("cpu")
    print("Using CPU")

# Custom Dataset class for easy integration with Hugging Face Trainer
class TextClassificationDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Create Dataset objects
train_dataset = TextClassificationDataset(train_encodings, y_train.tolist())
val_dataset = TextClassificationDataset(val_encodings, y_val.tolist())
test_dataset = TextClassificationDataset(test_encodings, y_test.tolist())

# Load the pre-trained model
# Set num_labels to the number of unique labels in your dataset
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=len(label_map))
model.to(device)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',          # output directory
    num_train_epochs=3,              # total number of training epochs
    per_device_train_batch_size=16,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./logs',            # directory for storing logs
    logging_steps=10,
    # evaluation_strategy="epoch",     # Evaluate every epoch - Removed due to TypeError
    # save_strategy="epoch",           # Save checkpoint every epoch - Removed as it relies on evaluation
    # load_best_model_at_end=True,     # Load the best model at the end of training - Removed as it relies on evaluation
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("\nStarting model training...")
# Train the model
trainer.train()
print("Model training complete.")

"""## Section 4: Evaluate Fine-Tuned Model

This section evaluates the fine-tuned model on the test set, prints per-class metrics, and generates a confusion matrix. The results will be saved to `evaluation_results.json` and `confusion_matrix.png`.
"""

from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

# Define compute_metrics function for the Trainer
def compute_metrics(p):
    predictions = np.argmax(p.predictions, axis=1)
    accuracy = accuracy_score(p.label_ids, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(p.label_ids, predictions, average=None, labels=list(label_map.values()))

    # Reverse label map for target names
    idx_to_label = {v: k for k, v in label_map.items()}
    target_names = [idx_to_label[i] for i in sorted(idx_to_label.keys())]

    metrics = {
        'accuracy': accuracy,
        'precision': {name: p_val for name, p_val in zip(target_names, precision)},
        'recall': {name: r_val for name, r_val in zip(target_names, recall)},
        'f1': {name: f_val for name, f_val in zip(target_names, f1)},
    }
    return metrics

print("\nEvaluating fine-tuned model on the test set...")
# Evaluate the model on the test dataset
predictions_output = trainer.predict(test_dataset)

# Get predictions and true labels
predictions = np.argmax(predictions_output.predictions, axis=1)
true_labels = test_dataset.labels

# Calculate overall accuracy
overall_accuracy = accuracy_score(true_labels, predictions)
print(f"Overall Accuracy (Fine-tuned model): {overall_accuracy:.4f}")

# Generate classification report
idx_to_label = {v: k for k, v in label_map.items()}
target_names = [idx_to_label[i] for i in sorted(idx_to_label.keys())]

print("\nClassification Report (Fine-tuned model):\n")
print(classification_report(true_labels, predictions, target_names=target_names))

# Generate Confusion Matrix
cm = confusion_matrix(true_labels, predictions, labels=list(label_map.values()))

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=target_names, yticklabels=target_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Fine-tuned Model)')
plt.tight_layout()
plt.savefig('confusion_matrix.png')
plt.show()

print("Confusion matrix saved as confusion_matrix.png")

# Save evaluation results to JSON
eval_results = compute_metrics(predictions_output)
# Add overall accuracy explicitly for clarity
eval_results['overall_accuracy'] = overall_accuracy

with open('evaluation_results.json', 'w') as f:
    json.dump(eval_results, f, indent=4)

print("Evaluation results saved to evaluation_results.json")

from google.colab import files

# Download the evaluation results JSON file
files.download('evaluation_results.json')

import torch.nn.functional as F
import numpy as np
from scipy.special import softmax

# Logits are in predictions_output.predictions
logits = predictions_output.predictions

# Convert logits to probabilities using softmax
probabilities = softmax(logits, axis=1)

print("Fine-tuned Model Predictions with Confidence (Test Set):\n")

# Iterate through the test set predictions
for i in range(len(test_dataset)):
    text_content = X_test.iloc[i]
    original_index = X_test.index[i]
    true_label_idx = true_labels[i]
    predicted_label_idx = predictions[i]
    confidence = probabilities[i, predicted_label_idx] * 100 # Percentage

    true_label_name = idx_to_label[true_label_idx]
    predicted_label_name = idx_to_label[predicted_label_idx]

    print(f"-- Post {i+1} (Original Dataset Index: {original_index}) --")
    print(f"Text:\n{text_content}\n")
    print(f"True Label: {true_label_name}")
    print(f"Predicted Label: {predicted_label_name}")
    print(f"Confidence: {confidence:.2f}%\n")

# Store specific examples for narration in markdown
# Example 1: Correct Prediction (educative)
correct_pred_text = X_test.iloc[0]
correct_pred_true_label = idx_to_label[true_labels[0]]
correct_pred_predicted_label = idx_to_label[predictions[0]]
correct_pred_confidence = probabilities[0, predictions[0]] * 100

# Example 2: Incorrect Prediction (entertaining -> sports-news)
incorrect_pred1_text = X_test.iloc[2] # original index 27
incorrect_pred1_true_label = idx_to_label[true_labels[2]]
incorrect_pred1_predicted_label = idx_to_label[predictions[2]]
incorrect_pred1_confidence = probabilities[2, predictions[2]] * 100

# Example 3: Incorrect Prediction (educative -> sports-news)
incorrect_pred2_text = X_test.iloc[3] # original index 17
incorrect_pred2_true_label = idx_to_label[true_labels[3]]
incorrect_pred2_predicted_label = idx_to_label[predictions[3]]
incorrect_pred2_confidence = probabilities[3, predictions[3]] * 100

"""### Analysis of Fine-Tuned Model Predictions

#### 1. Correct Prediction

**Original Index:** `20`
**Text:**
```
trying to get from 100 elo to 1200

Guys I've been watching Gotham chess for a bit, done all the puzzles on chess.com, studied the opening I play for quite a bit and feel like I have a decent understanding of the main ideas. But I just cannot get better. I'm stuck at around 100-200. What else should I do? Help me out.
```
**True Label:** `educative`
**Predicted Label:** `educative`
**Confidence:** `95.42%`

**Explanation:** This post is a clear request for guidance and learning resources to improve chess skills. The phrases "trying to get from 100 elo to 1200", "What else should I do? Help me out" directly indicate an intent to learn and receive education. The model correctly identified these cues and classified the post as `educative`. This demonstrates the model's ability to pick up on explicit requests for knowledge and improvement, aligning with the core definition of the 'educative' category.

#### 2. Incorrect Prediction

**Original Index:** `27`
**Text:**
```
168 years ago today, Paul Morphy arrived in Europe and began to play the most beautiful chess ever seen.

His games are an absolute delight. You should study them carefully.
```
**True Label:** `entertaining`
**Predicted Label:** `sports-news`
**Confidence:** `98.14%`

**Explanation:** This post recounts a historical event involving a famous chess player and encourages readers to study his games. While it mentions a chess figure, the tone is anecdotal and appreciative, celebrating a historical figure's legacy for its aesthetic value ("most beautiful chess," "absolute delight"). This content is primarily designed to be `entertaining` and inspiring. The model incorrectly classified it as `sports-news`. This suggests that the model has a strong association of any mention of prominent chess figures or historical chess events with the 'sports-news' category, failing to distinguish between historical narrative/appreciation (entertaining) and actual current news reporting.

#### 3. Another Incorrect Prediction

**Original Index:** `17`
**Text:**
```
Venting about the Catalan

Chess is such a beautiful game until you play the Catalan as black and you have to defend forever (or you blunder and lose in 20 moves). It's so hard to play. Any advice to play against it? (I'm a 1000 elo player)
```
**True Label:** `educative`
**Predicted Label:** `sports-news`
**Confidence:** `97.69%`

**Explanation:** This post describes a user's frustration with a specific chess opening ("Catalan") and explicitly asks for "Any advice to play against it?". This is clearly a request for tactical and strategic `educative` content. However, the model classified it as `sports-news`. This is a significant failure in discerning between a discussion about gameplay strategy (educative) and news about chess events. Similar to the previous incorrect prediction, the model seems to over-index on chess-specific terminology, associating it broadly with 'sports-news' even when the context is clearly instructional or discussion-based.
"""

print(f"Correct Prediction Confidence: {correct_pred_confidence:.2f}%")
print(f"Incorrect Prediction 1 Confidence: {incorrect_pred1_confidence:.2f}%")
print(f"Incorrect Prediction 2 Confidence: {incorrect_pred2_confidence:.2f}%")

"""## Error Pattern Analysis

The primary error pattern observed in the fine-tuned model's predictions is a **consistent over-classification of content into the `sports-news` category**, particularly when the text involves chess-specific terminology, game analysis, or historical chess figures. The model frequently mislabels `entertaining` and `educative` posts as `sports-news`.

**Supporting Evidence:**

1.  **Incorrect Prediction (Entertaining -> Sports-News):** The post about Paul Morphy's chess was classified as `sports-news` with high confidence (`98.14%`), despite its narrative and appreciative tone that clearly aligns with `entertaining` content. The model likely fixated on the mention of a prominent chess figure and a historical event, interpreting it as news.
2.  **Incorrect Prediction (Educative -> Sports-News):** The user's query about dealing with the 'Catalan' opening was also misclassified as `sports-news` with high confidence (`97.69%`). This post explicitly asked for advice (an educative intent), yet the presence of chess opening terminology led the model to incorrectly assign it to the `sports-news` category.

**Conclusion:**

This pattern suggests that the model has developed a strong association between **any mention of chess-related entities (players, openings, historical events) and the `sports-news` label**, irrespective of the actual intent or nature of the content (e.g., instructional, historical anecdote, discussion). It struggles to grasp the nuanced distinction between a report of a current event (true sports news) and a discussion, historical reflection, or request for education within the domain of chess.
"""

class SingleTextClassificationDataset(Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        return item

    def __len__(self):
        return len(self.encodings.input_ids)

def classify_new_post(post_text):
    # Tokenize the input text
    tokenized_input = tokenizer(post_text, truncation=True, padding=True, return_tensors="pt")

    # Create a dataset object for the single input
    single_dataset = SingleTextClassificationDataset(tokenized_input)

    # Make prediction using the trained trainer
    prediction_output = trainer.predict(single_dataset)

    # Get logits and convert to probabilities
    logits = prediction_output.predictions[0] # [0] because it's a single prediction
    probabilities = softmax(logits)

    # Get predicted label index and confidence
    predicted_label_idx = np.argmax(probabilities)
    confidence = probabilities[predicted_label_idx] * 100

    # Convert index back to label name
    idx_to_label = {v: k for k, v in label_map.items()}
    predicted_label_name = idx_to_label[predicted_label_idx]

    print(f"Predicted Label: {predicted_label_name}")
    print(f"Confidence: {confidence:.2f}%")

"""### Example Usage of the New Post Classifier"""

# Example 1: Educative Post
print("Classifying 'How to get better at chess openings?':")
classify_new_post("How to get better at chess openings? I always struggle in the first moves.")
print("\n---\n")

# Example 2: Sports News Post
print("Classifying 'Carlsen wins Norway Chess 2024':")
classify_new_post("Magnus Carlsen just won Norway Chess 2024 after a thrilling final round!")
print("\n---\n")

# Example 3: Entertaining Post
print("Classifying 'A funny story about my last game':")
classify_new_post("I played the funniest game of my life yesterday. My opponent blundered their queen on move 5!")